### ISSUE TITLE
A better translated version of datasheet?

### ISSUE THREAD

**Issue by Zhwt** [brianrho/FPM#30]
Hi, I have read the datasheet manual linked in the `README.md` file, and it looks wired on my computer, so I did a little search and found out that maybe the original version of that datasheet file is [this one from adafruit website](https://cdn-shop.adafruit.com/datasheets/DY001fingerprint.pdf). And now since adafruit provides a [translated version of the user manual](https://cdn-shop.adafruit.com/datasheets/ZFM+user+manualV15.pdf), could you please update the link so it points to a relatively better version of user manual?

And here is the link to adafruit's download page: https://learn.adafruit.com/adafruit-optical-fingerprint-sensor/downloads
Doing fingerprint-related development is a little harder due to lack of documents. 😂 I would suggest to add that link in README file too to provide more information.

**Comment by brianrho** [comment]
The reason I used that datasheet at the time, is because it's more complete than the one from Adafruit; some commands like ReadConList for reading the table of used IDs, aren't present in the Adafruit version. However, it's been a while since I put up that link so I should probably update it to something more recent, I think some of the newer sensors have the same complete command set and a neat PDF too.
