### ISSUE TITLE
How to synchronize prints between two modules.

### ISSUE THREAD

**Issue by one-player** [brianrho/FPM#5]
Tell me please.
For example, if I use two modules and one will fail. How do I make a module dump in order to unload it into a new module?

**Comment by brianrho** [comment]
If a module gets damaged, you probably cant interact with it anymore so you
should make sure you backup each template immediately after enrollment.

You can also obtain all the templates currently stored in a module;
assuming you have an existing database of the IDs of every print that has
been enrolled, you can query the module for the template at each ID
location, as shown in the "show_fingerprint_templates" example. You can
also dump a template from an array into a particular ID location in another
module.

Simply write some sketch that iterates through all the used IDs, and reads
each template into an array from module A and dumps it into the
corresponding ID location in module B. The example I mentioned shows how to
do read and write templates to the modules.

On Dec 19, 2017 11:00, "one-player" <notifications@github.com> wrote:

Tell me please.
For example, if I use two modules and one will fail. How do I make a module
dump in order to unload it into a new module?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/brianrho/FPM/issues/5>, or mute the thread
